pool:
  vmImage: ubuntu-latest

steps:
- script: |
    GIT_COMMIT=$( git rev-parse --short HEAD )
    echo "##vso[task.setvariable variable=GIT_COMMIT;isOutput=true]$GIT_COMMIT"
  name: runtime_vars
  displayName: 'Set runtime variables for pipeline'

- script: |
    packer build -force ado.json
  displayName: 'Execute Packer script for sequencing'
  env:
    AZURE_CLOUD: $(AZURE_CLOUD)
    AZURE_SECRET: $(sp-password-tf-5058)
    AZURE_CLIENTID: $(sp-client-id-tf-5058)
    AZURE_SUBSCRIPTIONID: $(sp-subscription-id-tf-5058)
    AZURE_TENANTID: $(sp-tenant-id-tf-5058)
    AZURE_LOCATION: $(AZURE_LOCATION)
    AZURE_RESOURCE_GROUP: $(AZURE_RESOURCE_GROUP)
    IMAGE_VERSION: $(runtime_vars.GIT_COMMIT)
